### PR TITLE
Use description field as subtitle for Atom feeds, if provided

### PR DESCRIPTION
**Pull request by venthur**
closes: #22

### CODE REVIEW

**Comment by justinmayer** [comment]
Any comments on this pull request? Even a cursory review would be most helpful. (Copying folks who have worked on Atom-related things in the past: @eevee @mosra @mauriciogardini)

**Comment by venthur** [comment]
The failing tests are unrelated to this pull request. the fix is in a seperate pull request.

**Comment by mauriciogardini** [comment]
> Any comments on this pull request? Even a cursory review would be most helpful. (Copying folks who have worked on Atom-related things in the past: @eevee @mosra @mauriciogardini)

Looks ok for me!

**Comment by venthur** [comment]
Hi,

any updates on this?

**Comment by justinmayer** [comment]
Thank you, Bastian, for your work and your patience. 💫

**Comment by venthur** [comment]
You're welcome! Any chance you'll release a new version soonish? I have a dependency on that fix, I'd like to pin in my `requirements.txt`

**Comment by justinmayer** [comment]
[FeedGenerator 1.9.2 has been released](https://github.com/getpelican/feedgenerator/releases/tag/1.9.2) containing this feature. ✨

**Pull request merged**
