### PR TITLE
Replace non-ASCII character in README

### LINKED ISSUE #19: setup.py fails with UnicodeDecodeError on FreeBSD 12.1-RELEASE-p6 under poudriere
When building the `www/py-feedgenerator` port in FreeBSD using the poudriere tool, the build fails in the "configure" phase with a `UnicodeDecodeError` traceback in `setup.py`. This affects multiple versions of Python 3.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 11, in <module>
    LONG_DESCRIPTION = open('README.rst').read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 422: ordinal not in range(128)
*** Error code 1
```

# Analysis

`setup.py` populates the contents of the package's `long_description` parameter by opening and reading the `README.rst` file. The file appears to be UTF-8 encoded, but `setup.py` does not specify an encoding, which causes the `open` function to fall back to guessing the encoding based on the platform and environment. In this case, Python guesses ASCII. Since `README.rst` includes a RIGHT SINGLE QUOTATION MARK (U+2019) character that cannot be represented in ASCII, the decode fails.

### PR DESCRIPTION
**Pull request by neirbowj**
This patch enables running setup.py in environments in which `locale.getpreferredencoding(False)` returns `'ASCII'` or any ASCII-compatible encoding.

Fixes #19

### CODE REVIEW

**Comment by justinmayer** [comment]
While I think the word "gratuitous" here is unnecessarily judgmental, I'm happy to entertain a more detailed description of the types of environments where the proper apostrophe poses a problem, as well as a more detailed description of what said problem is.

**Comment by neirbowj** [comment]
Thank you for that feedback. I have removed the objectionable word and will open a corresponding bug report to which this PR could become a candidate resolution.

**Comment by neirbowj** [comment]
An arguably superior alternative, which some other projects have adopted, would be to explicitly pass the `encoding` parameter to `open`. To retain backward compatibility with Python 2, it has to be passed conditionally, e.g. via `**kwargs`.

**Comment by avaris** [comment]
> An arguably superior alternative, which some other projects have adopted, would be to explicitly pass the `encoding` parameter to `open`. 

Yes, let's do that please.

> To retain backward compatibility with Python 2, it has to be passed conditionally, e.g. via `**kwargs`.

```python
from io import open
```
then you can use `encoding` in both python2 and python3

**Comment by neirbowj** [comment]
@avaris Great tip!

**Comment by justinmayer** [comment]
Closing in favor of #20, which has been merged.

**Pull request closed without merging**
