### PR TITLE
Remove Python 2

### LINKED ISSUE #26: which python versions do you want to support?
currently there's a mix of various seemingly supported python versions in the repo:
* `.github/workflows/main.yml`: tests against py37..py39
* `setup.py` claims: py27, py35..py38
* `tox.ini` claims: py26, py27, py32..py35

which versions do you want to support? i propose do drop python2 completely and remove make py36 the oldest supported version for now.

### PR DESCRIPTION
**Pull request by venthur**
This is a giant diff, I know but it basically does this:
* remove all __future__ imports and explicit file encodings
* remove six with all implications
* remove python2 specific code
* added py36 as min required version

there might be some more subtle python2 specific code hidden in there

closes #26

### CODE REVIEW

**Comment by justinmayer** [comment]
Looks good to me. I'll follow up with a few more modernizations as well. Anything else needed here before merging this PR?

**Comment by venthur** [comment]
Not from my side. I assume there's some more code "hidden" in there that is now unused, for example regarding the unicode conversion. I believe you're more experienced with the code than me to make that call. Looking at the lines missing from the coverage report could help here.

**Comment by justinmayer** [comment]
Yeah, I actually don't have much personal experience with this code, so unfortunately I'm not well-positioned to make that call. But perhaps @avaris might have some thoughts on the matter.

**Comment by justinmayer** [comment]
For now, let's merge this and continue the endeavor via subsequent PRs. Thanks for you work on this, Bastian! 💯

**Pull request merged**
